language: objective-c
osx_image: xcode9
script:
  - swiftlint
  - xcodebuild test -workspace Example/Example.xcworkspace -scheme Example -destination 'platform:tvOS Simulator, OS:11.0, name:Apple TV 4K'
