language: objective-c
osx_image: xcode8.3
script:
  - swiftlint
  - xcodebuild test -workspace Example/Example.xcworkspace -scheme Example -destination 'platform=tvOS Simulator,name=Apple Tv (11.1),OS=11.1'
